# Generated by Django 5.1.2 on 2025-11-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_alter_ingredient_expiry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('catch_copy', models.TextField(blank=True, null=True)),
                ('foodImageUrl', models.URLField(blank=True, null=True)),
                ('recipeUrl', models.URLField(blank=True, null=True)),
                ('recipeCost', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredients', models.JSONField(default=list)),
                ('instructions', models.JSONField(default=list)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('main_nutrients', models.JSONField(default=list)),
                ('cooking_point', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
    ]
